spring:
  datasource:
    url: jdbc:mysql://localhost/spring?serverTimezone=UTC
    username: root
    password: pablo1406
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false

